%YAML:1.0
---

# 传感器模式，共6种基本形式，可以任意组合，以加号连接：color, infra1, infra2, depth, accel, gyro
sensor_mode: accel+gyro

# RGB相机与彩色影像数据相关
# ---------------------------------------------
# color有多种可选：yuyv, bgr8, rgb8, y16, raw16
data_format_color: raw16

# 彩色影像长宽，有多种预置：1920x1080, 1280x720, 960x540, 848x480, 640x480等
frame_width_color: 1920
frame_height_color: 1080

# 彩色影像帧率
frame_rate_color: 30

# 是否开启自动曝光, 1表示开启, 0表示关闭
enable_AE_color: 1

# 如果是手动曝光，设置曝光量
manual_exposure_color: 166
# ---------------------------------------------


# 红外相机与红外影像数据相关
# ---------------------------------------------
# infra有两种可选：y8, y16
data_format_infra: y16

# 红外影像长宽，有多种预置：1280x800, 1280x720, 848x480, 640x480等
frame_width_infra: 1280
frame_height_infra: 800

# 红外影像帧率
frame_rate_infra: 25

# 是否开启自动曝光, 1表示开启, 0表示关闭
enable_AE_infra: 1

# 如果是手动曝光，设置曝光量
manual_exposure_infra: 500

# 是否开启红外发射器，默认为关闭
enable_emitter: 1

# 红外相机模式，1-left,2-right,3-both
infra_mode: 3
# ---------------------------------------------


# 深度相机与深度影像数据相关
# ---------------------------------------------
# depth有一种可选：z16
data_format_depth: z16

# 深度影像长宽，有多种预置：1280x800, 1280x720, 848x480, 640x480等
frame_width_depth: 848
frame_height_depth: 480

# 深度影像帧率
frame_rate_depth: 30
# ---------------------------------------------


# IMU(加速度计)相关
# ---------------------------------------------
# 只有一种可选：xyz32f
data_format_accel: xyz32f

# 两种可选：63, 250
frame_rate_accel: 250
# ---------------------------------------------


# IMU(陀螺仪)相关
# ---------------------------------------------
# 只有一种可选：xyz32f
data_format_gyro: xyz32f

# 两种可选：200, 400
frame_rate_gyro: 200
# ---------------------------------------------


# 可视化与输出相关
# ---------------------------------------------
# 是否只可视化，1表示只可视化，2表示只保存，3表示可视化+保存
# 为了获得最好的保存效果，建议需要输出的时候只保存，不可视化
view_mode: 3

# 保存影像输出路径
output_dir_image: "./frames"
# 保存影像输出类型，对于非8bit数据，推荐用无损的png格式
output_type_image: ".png"

# 保存IMU(加速度计)输出路径
output_dir_accel: "./frames"
# 保存IMU(加速度计)输出类型
output_type_accel: ".txt"

# 保存IMU(陀螺仪)输出路径
output_dir_gyro: "./frames"
# 保存IMU(陀螺仪)输出类型
output_type_gyro: ".txt"
# ---------------------------------------------